version: '3.8'

services:
  homepage:
    build: .
    ports:
      - "${SERVER_PORT}:${NGINX_PORT}"
    restart: unless-stopped
    environment:
        - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
